# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0020_courseoverview_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='availability',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courseoverview',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
