# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-11-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0021_auto_20190801_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='main_page',
            field=models.BooleanField(default=False),
        ),
    ]
