# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-11-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_creators', '0002_auto_20180814_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreator',
            name='note',
            field=models.CharField(blank=True, help_text='Opcjonalne notatki dotycz\u0105ce tego u\u017cytkownika (np. dlaczego zosta\u0142 mu odm\xf3wiony dost\u0119p do kreatora kursu)', max_length=512),
        ),
    ]
