# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-01-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0008_auto_20180814_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccessrequest',
            name='reason',
            field=models.TextField(help_text='Pow\xf3d, dla kt\xf3rego u\u017cytkownik \u017c\u0105da dost\u0119pu do API.'),
        ),
    ]
