# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-06-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_task', '0002_gradereportsetting'),
        ('certificates', '0015_certificategenerationmergehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificategenerationmergehistory',
            name='instructor_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='instructor_task.InstructorTask'),
            preserve_default=False,
        ),
    ]
