# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-06-15 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_certificategenerationmergehistory_instructor_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificategenerationmergehistory',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
