# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-06-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_auto_20200615_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificategenerationmergehistory',
            name='pdf',
            field=models.FileField(upload_to=b'merge_certificates/%Y/%m/%d/'),
        ),
    ]
