# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_delete_historical_credit_records'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequirementstatus',
            options={'verbose_name_plural': 'Statusy wymaga\u0144 kwalifikacji.'},
        ),
        migrations.AlterField(
            model_name='creditconfig',
            name='cache_ttl',
            field=models.PositiveIntegerField(default=0, help_text="Okre\u015blony w sekundach. W\u0142\u0105cz cache'owanie ustawiaj\u0105c t\u0119 warto\u015b\u0107 na wi\u0119ksz\u0105 od 0.", verbose_name='Cache czasu \u017cycia pakietu'),
        ),
    ]
