# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-01-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_template_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter_emails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
