# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_manualenrollmentaudit_add_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiency',
            name='code',
            field=models.CharField(choices=[['pl', 'polski'], ['en', 'angielski']], help_text='The ISO 639-1 language code for this language.', max_length=16),
        ),
    ]
